### ISSUE TITLE
Date columns as integer

### ISSUE THREAD

**Issue by fsnow** [rjrudin/nifi-rowtodoc#1]
With SQLToColumnMaps and ConvertColumnMapsToJSON, the date columns are coming out as long integers, e.g.:

"hire_date": 907743600000,

Using MySQL 8.0 on Windows. NiFi 1.7.1.

**Comment by rjrudin** [comment]
Are you able to share the dataset? 

The code is using Spring's ColumnMapRowMapper. That depends on a Spring method - JdbcUtils.getResultSetValue - to get the value out of each column. In theory, what you're getting are the correct values in Spring's opinion.

**Comment by rjrudin** [comment]
Specifically, I wonder if this condition in JdbcUtils.getResultSetValue is evaluating to true, thus resulting in a timestamp (a long integer) being returned:

    else if (obj instanceof Date && "java.sql.Timestamp".equals(rs.getMetaData().getColumnClassName(index))) {
                obj = rs.getTimestamp(index);
            }

**Comment by fsnow** [comment]
This is the dataset:
https://github.com/datacharmer/test_db

MySQL Workbench lists all the affected columns as type "date".

![employees-types](https://user-images.githubusercontent.com/1839157/45103206-300d2500-b0e4-11e8-9377-4f1d58b9b077.png)

**Comment by rjrudin** [comment]
I'm able to reproduce this, stepping through the debugger now to see how it ends up as a numeric value.

**Comment by rjrudin** [comment]
Ah - the value is mapped correctly to a java.sql.Date, but the default Jackson JSON serialization converts it into a number.

**Comment by rjrudin** [comment]
@fsnow I can easily add a property to the JSON serializer processor to control the format that java.sql.Date objects are serialized to. For now, that'll be for all instances of java.sql.Date. In the future, I can envision a UI for specifying a format per JSON property name.

Sound good?

**Comment by fsnow** [comment]
Yes. Thanks!

**Comment by rjrudin** [comment]
See https://github.com/rjrudin/nifi-rowtodoc/pull/4
